spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.255.2.146:1521:pandb
    username: posp
    password: posp
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
      reset-enable: false
      login-username: dev
      login-password: dev
      allow: 127.0.0.1
      deny: 192.0.0.1