spring:
  datasource:
    druid:
      master:
        url: jdbc:postgresql://10.255.2.197:5432/hsy_core?autosave=conservative
        username: postgres
        password: pg@chanjet
        driver-class-name: org.postgresql.Driver
        initial-size: 0
        max-active: 60
        min-idle: 2
        max-wait: 5000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        validation-query: 'SELECT 1'
        validation-query-timeout: 1000
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 6000
        min-evictable-idle-time-millis: 600000
        max-evictable-idle-time-millis: 25200000
        keep-alive: true
        fail-fast: true
        filters: mergeStat,wall,slf4j
        web-stat-filter:
          enabled: true
          url-pattern: /*
          exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        stat-view-servlet:
          enabled: true
          url-pattern: /druid/*
          reset-enable: false
          login-username: dev
          login-password: dev
          allow: 127.0.0.1
          deny: 192.0.0.1
      slave:
        url: jdbc:postgresql://10.255.2.199:5432/hsy_core?autosave=conservative
        username: postgres
        password: pg@chanjet
        driver-class-name: org.postgresql.Driver
        initial-size: 0
        max-active: 60
        min-idle: 2
        max-wait: 5000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        validation-query: 'SELECT 1'
        validation-query-timeout: 1000
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 6000
        min-evictable-idle-time-millis: 600000
        max-evictable-idle-time-millis: 25200000
        keep-alive: true
        fail-fast: true
        filters: mergeStat,wall,slf4j
        web-stat-filter:
          enabled: true
          url-pattern: /*
          exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        stat-view-servlet:
          enabled: true
          url-pattern: /druid/*
          reset-enable: false
          login-username: dev
          login-password: dev
          allow: 127.0.0.1
          deny: 192.0.0.1