server:
  port: 19101

spring:
  application:
    name: creepin-service
  cloud:
    config:
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
      label: master
      discovery:
        enabled: true
        service-id: config-server
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:pandb
    username: posp
    password: posp
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.server.ip-address:127.0.0.1}:${eureka.server.port:19001}/eureka/

mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml

mapper:
  not-empty: false
  mappers: tk.mybatis.mapper.common.Mapper